### ISSUE TITLE
Command argument should not be required

### ISSUE THREAD

**Issue by javiercr** [wercker/step-kubectl#15]
I'm using this step (actually it's [riceo's fork](https://github.com/riceo/step-kubectl)) just to install and setup kubectl and then I'm using [helm](http://helm.sh/) to perform the deploy.

The kubectl step is requiring a value for the `command` argument, however I don't really need it. Would  it be worth to **reconsider making `command` optional?** 

In the meantime I just fixed it by passing a command that does nothing (`command: version`).

**Comment by hatchan** [comment]
This step does not install the `kubectl` binary on the container. kubectl is bundled with the step and only available for that the step. Please submit an issue to the forked repo for any feature requests for that step, as that will be moved into a separate step.

**Comment by javiercr** [comment]
Hey @hatchan sorry for the confusion, I totally assumed this step would download and install `kubectl` (not `gcloud`). Maybe a clarification in the docs would be helpful?  Thanks!
